import jsPDF from 'jspdf';
import { formatCurrency, formatDate } from '@/lib/utils';
import type { Dealer } from '@/types/database';

const safeCurrency = (val: number) => formatCurrency(val).replace(/₹/g, 'Rs ');

export const generateDailySummaryPdfBlob = async (
  stats: any,
  dealer: Dealer | null,
): Promise<Blob> => {
  const doc = new jsPDF('p', 'mm', 'a5'); // A5 size is good for a daily summary
  const margin = 15;
  let yPos = margin;
  const pageWidth = doc.internal.pageSize.getWidth();

  // --- Header ---
  doc.setFontSize(18);
  doc.setTextColor(30, 58, 138); // blue
  doc.setFont('helvetica', 'bold');
  doc.text('DAILY SUMMARY', margin, yPos);

  if (dealer?.shop_name) {
    yPos += 8;
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(dealer.shop_name, margin, yPos);
  }

  yPos += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Date: ${formatDate(new Date().toISOString())}`, margin, yPos);

  yPos += 15;

  // --- Stats Table ---
  doc.setDrawColor(200, 200, 200);
  
  const drawRow = (label: string, value: string, isBold: boolean = false, isHeader: boolean = false) => {
    if (isHeader) {
      doc.setFillColor(240, 240, 240);
      doc.rect(margin, yPos, pageWidth - 2 * margin, 8, 'F');
    }
    
    doc.setFont('helvetica', isBold || isHeader ? 'bold' : 'normal');
    doc.setTextColor(isHeader ? 50 : 0);
    doc.text(label, margin + 2, yPos + 5);
    doc.text(value, pageWidth - margin - 2, yPos + 5, { align: 'right' });
    
    yPos += 8;
    doc.line(margin, yPos, pageWidth - margin, yPos);
  };

  doc.line(margin, yPos, pageWidth - margin, yPos);
  
  drawRow('Sales & Billing', '', true, true);
  drawRow('Total Sales Today', safeCurrency(stats?.todaySales || 0), true);
  yPos += 3;
  drawRow('Total Cash Sales', safeCurrency(stats?.todayCashSales || 0));
  drawRow('Total UPI Sales', safeCurrency(stats?.todayUpiSales || 0));

  yPos += 5;
  drawRow('Cash Received', safeCurrency(stats?.todayCashReceived || 0));
  drawRow('UPI Received', safeCurrency(stats?.todayUpiReceived || 0));

  yPos += 5;
  drawRow('New Customers', `${stats?.newFarmersToday || 0}`);
  
  yPos += 5;
  drawRow('Credit Given Today', safeCurrency(stats?.todayCredit || 0));
  drawRow('Total Outstanding Dues', safeCurrency(stats?.totalDues || 0), true);

  yPos += 15;

  // --- Footer ---
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by AquaDealer', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  return doc.output('blob');
};

export const shareDailySummaryViaWhatsApp = async (
  stats: any, 
  dealer: Dealer | null
): Promise<void> => {
  const { sharePdfViaWhatsApp } = await import('@/lib/shareUtils');
  const blob = await generateDailySummaryPdfBlob(stats, dealer);
  
  const fallbackText = `*${dealer?.shop_name || 'AquaDealer'}*\n-------------------\n*Daily Summary (${formatDate(new Date().toISOString())})*\n*Sales:* ${formatCurrency(stats?.todaySales || 0)}\n*Cash Recv:* ${formatCurrency(stats?.todayCashReceived || 0)}\n*Credit Given:* ${formatCurrency(stats?.todayCredit || 0)}\n-------------------\nPlease find the detailed summary PDF attached.`;
  
  await sharePdfViaWhatsApp(blob, `Daily_Summary_${new Date().toISOString().split('T')[0]}.pdf`, fallbackText);
};
