import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly } from 'workbox-strategies';


cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Setup Background Sync for Supabase REST and RPC calls
const bgSyncPlugin = new BackgroundSyncPlugin('supabase-offline-queue', {
  maxRetentionTime: 24 * 60, // Retry for max of 24 Hours (specified in minutes)
});

// Register route for Supabase POST, PUT, PATCH, DELETE requests
registerRoute(
  ({ url, request }) => 
    url.origin.includes('supabase.co') && 
    (request.method === 'POST' || request.method === 'PATCH' || request.method === 'PUT' || request.method === 'DELETE'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'POST'
);
registerRoute(
  ({ url, request }) => 
    url.origin.includes('supabase.co') && 
    (request.method === 'POST' || request.method === 'PATCH' || request.method === 'PUT' || request.method === 'DELETE'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'PUT'
);
registerRoute(
  ({ url, request }) => 
    url.origin.includes('supabase.co') && 
    (request.method === 'POST' || request.method === 'PATCH' || request.method === 'PUT' || request.method === 'DELETE'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'PATCH'
);
registerRoute(
  ({ url, request }) => 
    url.origin.includes('supabase.co') && 
    (request.method === 'POST' || request.method === 'PATCH' || request.method === 'PUT' || request.method === 'DELETE'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'DELETE'
);

// Skip waiting and claim clients
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
