import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkOnly, NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Clean up old caches from previous versions
cleanupOutdatedCaches();

// Precache all assets generated by Vite (JS, CSS, HTML, images, fonts)
// self.__WB_MANIFEST is injected by vite-plugin-pwa at build time
precacheAndRoute(self.__WB_MANIFEST || []);

// SPA Navigation Fallback: serve /index.html for all navigation requests
// This is critical for offline — without it, navigating to /dashboard or /billing
// when offline returns a network error instead of loading the cached SPA shell.
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler, {
  // Don't intercept Supabase auth callback URLs
  denylist: [/^\/auth/, /^\/api/],
});
registerRoute(navigationRoute);

// Cache Supabase GET requests (data reads) with NetworkFirst strategy
// This means: try network first, fall back to cached data if offline
registerRoute(
  ({ url, request }) =>
    url.origin.includes('supabase.co') && request.method === 'GET',
  new NetworkFirst({
    cacheName: 'supabase-data-cache',
    networkTimeoutSeconds: 3, // Fallback to cache if network takes too long (Lie-Fi)
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 60 * 60 * 24, // 24 hours
      }),
    ],
  })
);

// Cache Google Fonts with CacheFirst (they rarely change)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

// Setup Background Sync for Supabase write operations (POST, PUT, PATCH, DELETE)
// When offline, these requests are queued and replayed when connectivity returns
const bgSyncPlugin = new BackgroundSyncPlugin('supabase-offline-queue', {
  maxRetentionTime: 24 * 60, // Retry for max of 24 Hours (specified in minutes)
});

// Register background sync for table mutation methods.
// RPC calls (/rest/v1/rpc/...) are excluded: bill creation is handled by the
// app-level offline queue (offlineBillStore) with an idempotency ref, and
// blindly replaying other RPCs could double-apply stock/cash movements.
['POST', 'PUT', 'PATCH', 'DELETE'].forEach((method) => {
  registerRoute(
    ({ url, request }) =>
      url.origin.includes('supabase.co') &&
      request.method === method &&
      !url.pathname.includes('/rpc/'),
    new NetworkOnly({
      plugins: [bgSyncPlugin],
    }),
    method
  );
});

// Allow the web app to trigger skipWaiting via postMessage
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
